dialogo = input("o seu numero da sorte é a soma do seu mes de nascimento com o dia do seu nascimento! ")
mes = input("Digite o mês do seu nascimento (1-12): ")
dia = input("Digite o dia do seu nascimento (1-31): ")
numero_da_sorte = int(mes) + int(dia)
print("Seu número da sorte é: ", numero_da_sorte)